version: '3'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: movies
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongors1n1:
    container_name: mongors1n1
    image: mongo
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27017
    ports:
      - 27017:27017
    expose:
      - "27017"
    volumes:
      - mongodata1:/data/db
  mongocfg1:
    container_name: mongocfg1
    image: mongo
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - mongocfg1:/data/db
  mongos1:
    container_name: mongos1
    image: mongo
    depends_on:
      - mongocfg1
    command: mongos --configdb mongors1conf/mongocfg1:27017 --port 27017
    ports:
      - 27019:27017
    expose:
      - "27017"

volumes:
  mongodata1:
  mongocfg1: